
html {
    head {
        title element.name
        link rel:'stylesheet', type:'text/css', href:'lappsstyle.css'
    }
    body {
        div(id:'container') {
            div(id:'mainContent') {
                p(class:'head') {
                    parents.each { parent ->
                        a(href:"${parent.name}.html", parent.name)
                        span ' > '
                    }
                    span element.name
                }
                p element.definition
                table(class:'definition-table') {
                    if (element.sameAs.size() > 0) {
                        tr {
                            td { b "Same as" }
                            td {
                                element.sameAs.collect { a(href:it, it) }.join(" ")
                            }
                        }
                    }
                    if (element.similarTo.size() > 0) {
                        tr {
                            td { b "Similar to" }
                            td {
                                element.similarTo.collect { a(href:it, it) }.join(" ")
                            }
                        }
                    }
                    tr {
                        td { b "URI" }
                        td element.uri
                    }
                }
                //def parent = element.parent
                while (element) {
                    if (element.properties.size() > 0) {
//                        String link = "<a href='${element.name}'>${element.name}</a>"
                        h2 "Properties from ${element.name}"
                        table(class: 'definition-table') {
                            tr {
                                //td { b "Properties" }
                                //td { b "Type" }
                                //td { b "Description" }
                                th "Properties"
                                th "Type"
                                th "Description"
                            }
                            List names = element.properties.keySet().asList().sort()
                            names.each { name ->
                                tr {
                                    def property = element.properties[name]
                                    td name
                                    td property.type
                                    td property.description
                                }
                            }
                        }
                    }
                    element = elements[element.parent]
                }
            }
        }
        div(id:'footer', 'Page generated by the MarkupBuilderTemplateEngine.')
    }
}
/**
 * Created by Nathan on 8/1/2014.
 */
