#!/bin/sh

set -e

# Startup script for the LAPPS Vocabulary processor.

MEMSIZE=4G
JAR=__JAR__

if [ "$1" = "-default" ] ; then
    if [ "$2" = "" ] ; then
        output=html
    else
        output=$2
    fi
    java -jar $JAR -d lapps.vocab -i table-index.groovy -h template.groovy -o $output
    exit
fi

java -jar $JAR $@
