#!/bin/sh

set -e

# Startup script for the LAPPS Vocabulary processor. Change the vocab installation directory
# below if needed.
#
MEMSIZE=4G
VERSION=__VERSION__
JAR=$HOME/bin/vocab-$VERSION.jar

java -jar $JAR $@
